declare module 'react-native-ico-miscellaneous' {
    import { ReactNode } from 'react';
    import { SvgProps, AdditionalProps } from 'react-native-svg';

    type iconNames = 'down-arrow' |
      'up-arrow' |
      'left-arrow' |
      'right-arrow' |
      'diagonal-arrow' |
      'diagonal-arrow-1' |
      'diagonal-arrow-2' |
      'diagonal-arrow-3' |
      'double-arrow' |
      'double-arrow-1' |
      'bus' |
      'truck' |
      'ambulance' |
      'helicopters' |
      'sailboat' |
      'cable-car-cabin' |
      'shop' |
      'groceries-store' |
      'pagoda' |
      'coffee-cup' |
      'sort' |
      'food-cart' |
      'mosque' |
      'building' |
      'police-box' |
      'caravan' |
      'school' |
      'kayak' |
      'skyscraper' |
      'building-1' |
      'bonfire' |
      'exchange' |
      'tent' |
      'house' |
      'hospital' |
      'factory' |
      'city-hall' |
      'city' |
      'bridge' |
      'ferris-wheel' |
      'billboard' |
      'phone-booth' |
      'expand' |
      'bus-stop' |
      'turn-right' |
      'street-light' |
      'hotel' |
      'obelisk' |
      'electric-tower' |
      'signboard' |
      'traffic-light' |
      'hydrant' |
      'bench' |
      'move' |
      'fountain' |
      'panels' |
      'mountain' |
      'barn' |
      'desert' |
      'trees' |
      'house-1' |
      'sun-umbrella' |
      'island' |
      'waterfall' |
      'expand-1' |
      'windmill' |
      'helm' |
      'anchor' |
      'umbrella' |
      'polaroids' |
      'lifesaver' |
      'suitcase' |
      'earth-globe' |
      'flight' |
      'heart' |
      'compress' |
      'download' |
      'upload' |
      'search' |
      'image' |
      'trash' |
      'attachment' |
      'edit' |
      'email' |
      'shopping-cart' |
      'user' |
      'curve-arrow' |
      'add-user' |
      'cloud' |
      'bug' |
      'fire' |
      'copyright' |
      'star' |
      'star-1' |
      'notification' |
      'notification-1' |
      'volume' |
      'curve-arrow-1' |
      'list' |
      'check' |
      'expand-2' |
      'subtitles' |
      'paper-plane' |
      'zoom-in' |
      'zoom-out' |
      'settings' |
      'file' |
      'file-1' |
      'curved-arrow' |
      'add-file' |
      'file-2' |
      'file-3' |
      'edit-file' |
      'audio-file' |
      'image-1' |
      'video-file' |
      'file-4' |
      'video-camera' |
      'video-camera-1' |
      'curve-arrow-2' |
      'phone-call' |
      'phone-call-1' |
      'photo-camera' |
      'wall-clock' |
      'refresh' |
      'padlock' |
      'open-padlock' |
      'price-tag' |
      'inbox' |
      'outbox' |
      'down-chevron' |
      'cancel' |
      'warning' |
      'question' |
      'chat' |
      'calendar' |
      'folder' |
      'like' |
      'thumb-down' |
      'filter' |
      'worldwide' |
      'up-chevron' |
      'smartphone' |
      'tablet' |
      'personal-computer' |
      'diskette' |
      'logout' |
      'menu' |
      'menu-1' |
      'menu-2' |
      'credit-card' |
      'eye' |
      'left-chevron' |
      'hide' |
      'crown' |
      'paint-palette' |
      'undo' |
      'redo' |
      'opacity' |
      'copy' |
      'layers' |
      'sheet' |
      'shield' |
      'right-chevron' |
      'quotation' |
      'cookie' |
      'link' |
      'book' |
      'coupon' |
      'cursor' |
      'cursor-1' |
      'suitcase-1' |
      'group' |
      'conference' |
      'down-chevron-1' |
      'deal' |
      'id-card' |
      'human-resources' |
      'goal' |
      'meeting' |
      'elderly' |
      'insurance' |
      'user-1' |
      'time-management' |
      'strategy' |
      'up-chevron-1' |
      'workflow' |
      'pyramid-chart' |
      'profits' |
      'loss' |
      'bar-chart' |
      'profits-1' |
      'loss-1' |
      'pie-chart' |
      'bar-chart-1' |
      'agenda' |
      'left-chevron-1' |
      'flower' |
      'pamela' |
      'branch' |
      'winter' |
      'rainy' |
      'rainy-1' |
      'rainy-2' |
      'umbrella-1' |
      'cloud-1' |
      'clouds' |
      'right-chevron-1' |
      'cloudy-night' |
      'sun' |
      'thermometer' |
      'thermometer-1' |
      'thermometer-2' |
      'thermometer-3' |
      'thermometer-4' |
      'drop' |
      'windy' |
      'wind' |
      'shuffle' |
      'wind-1' |
      'wind-2' |
      'snow' |
      'snowflake' |
      'snowflake-1' |
      'windy-1' |
      'hail' |
      'rainbow' |
      'rainbow-1' |
      'rainbow-2' |
      'recycle' |
      'rainbow-3' |
      'storm' |
      'bolt' |
      'cloudy' |
      'cloudy-1' |
      'cloudy-2' |
      'eclipse' |
      'moon-phase' |
      'moon-phase-1' |
      'moon-phase-2' |
      'split' |
      'moon-phase-3' |
      'moon-phase-4' |
      'moon-phase-5' |
      'half-moon' |
      'hurricane' |
      'foggy' |
      'co2' |
      'humidity' |
      'tornado' |
      'basketball' |
      'merge' |
      'baseball' |
      'football' |
      'volleyball' |
      'rugby-ball' |
      'tennis' |
      'bowling' |
      'ice-skate' |
      'roller-skate' |
      'skateboard' |
      'karate' |
      'u-turn' |
      'ice-hockey' |
      'golf' |
      'boxing' |
      'surfboard' |
      'dart' |
      'goal-1' |
      'badminton' |
      'ping-pong' |
      'racket' |
      'soccer-field' |
      'split-1' |
      'basketball-court' |
      'tennis-court' |
      'american-football' |
      'mountain-1' |
      'mountain-2' |
      'mountain-3' |
      'night' |
      'rainbow-4' |
      'barn-1' |
      'trees-1' |
      'split-2' |
      'desert-1' |
      'road' |
      'sunrise' |
      'sunset' |
      'beach-house' |
      'sunbed' |
      'island-1' |
      'sailboat-1' |
      'waterfall-1' |
      'windmill-1' |
      'triple-arrows' |
      'plant' |
      'flower-1' |
      'sprout' |
      'plant-1' |
      'wheat' |
      'harvest' |
      'rose' |
      'poppy' |
      'tulip' |
      'pinwheel' |
      'happy' |
      'fruit-tree' |
      'tree' |
      'pine' |
      'pine-1' |
      'palm-tree' |
      'cactus' |
      'recycle-1' |
      'sprout-1' |
      'save-water' |
      'faucet' |
      'sad' |
      'ecology' |
      'cat' |
      'dog' |
      'horse' |
      'bird' |
      'rabbit' |
      'butterfly' |
      'deer' |
      'sheep' |
      'monkey' |
      'meh' |
      'burger' |
      'pizza' |
      'sandwich' |
      'hot-dog' |
      'chicken-leg' |
      'french-fries' |
      'tomato' |
      'onion' |
      'bell-pepper' |
      'cabbage' |
      'support' |
      'corn' |
      'pumpkin' |
      'eggplant' |
      'carrot' |
      'broccoli' |
      'avocado' |
      'pear' |
      'strawberry' |
      'pineapple' |
      'orange' |
      'support-1' |
      'banana' |
      'watermelon' |
      'grapes' |
      'cherry' |
      'bread' |
      'steak' |
      'cheese' |
      'fried-egg' |
      'soup' |
      'salad' |
      'information' |
      'fish' |
      'shrimp' |
      'crab' |
      'cake' |
      'muffin' |
      'pancakes' |
      'water' |
      'milk' |
      'soda' |
      'wine' |
      'question-1' |
      'energy-drink' |
      'tea-cup' |
      'coffee-cup-1' |
      'beer' |
      'warning-1' |
      'chat-1' |
      'calendar-1' |
      'help' |
      'cone' |
      'counterclockwise' |
      'headphones' |
      'key' |
      'server' |
      '24-hours' |
      'target' |
      'target-1' |
      'target-2' |
      'pin' |
      'pin-1' |
      'pin-2' |
      'pin-3' |
      'pin-4' |
      'pin-5' |
      'flag' |
      'pin-6' |
      'pin-7' |
      'finger' |
      'position' |
      'position-1' |
      'compass' |
      'wind-rose' |
      'cursor-2' |
      'route' |
      'distance' |
      'pin-8' |
      'worldwide-1' |
      'internet' |
      'internet-1' |
      'internet-2' |
      'map' |
      'map-1' |
      'map-2' |
      'map-3' |
      'map-4' |
      'map-5' |
      'map-6' |
      'map-7' |
      'panel' |
      'bookmark' |
      'wifi' |
      'car' |
      'taxi' |
      'flight-1' |
      'boat' |
      'rocket' |
      'metro' |
      'train' |
      'tram' |
      'motorcycle' |
      'bicycle';

    type backgroundType = 'circle' | 'rect' | 'button';

    type positionType = 'top' | 'bottom' | 'right' | 'left' |
      'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';

    type backgroundTypeObj = {
      type?: backgroundType;
      color?: string;
      radius?: number;
      borderRadius?: number;
    };

    type badgeTypeObj = {
      value?: number | string;
      fontSize?: string;
      position?: positionType;
      color?: string;
      backgroundColor?: string;
      radius?: number;
    };

    interface IconProps {
      name: iconNames;
      width?: number;
      height?: number;
      color?: string;
      stroke?: number;
      background?: backgroundType | backgroundTypeObj;
      badge?: number | string | badgeTypeObj;
    }

    const Icon: (props: IconProps & SvgProps & AdditionalProps) => ReactNode;

    export { iconNames };
    export default Icon;
}
